[package]
name = "clockem"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
gdk4 = "0.9.5"
gio = "0.20.7"
glib = "0.20.7"
gtk4 = "0.9.5"
gtk4-layer-shell = "0.4.0"
pango = "0.20.7"
