[clock]
enabled = true
top_format = "%I:%M %p"     # date format string, use command date --help to view formatting options
bottom_format = "%b %d, %Y" # same date format string
position_x = 0              # position in pixels from left edge of the display
position_y = 0              # position in pixels from top edge of display; affected by things like waybar
y_align = "top"             # options are "center", "bottom", and "top"; top if invalid
update_interval = 1         # interval, in seconds, between updates

[wallpaper] # for now, the wallpaper image will always display at full scale, so it must be the resolution of your display to appear properly.
enabled = false
directory = "~/Pictures/Wallpaper/wallpaper.jpg"
vert_adjustment = 35                             # may need to be used if a bar like waybar is causing a gap between wallpaper and top of display.
